logging:
  level:
    root: INFO
spring:
  main:
    banner-mode: off
    web-application-type: none
  application:
    name: astrowidja-springshell

astrowidja:
    working-dir: "astrowidja"
    settings: "settings.ini"
    base-dir: "base"
